# Sohybe Ibrahim Abdelwahab Amer
## 222250182

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn import datasets
from sklearn.preprocessing import StandardScaler


In [3]:
iris = datasets.load_iris()
x = iris.data
y = iris.target

In [4]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
sclaer = StandardScaler()
x_std = sclaer.fit_transform(x)


In [7]:
x_std

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [11]:
clf = OneVsRestClassifier(LogisticRegression(random_state=0))

In [12]:
model = clf.fit(x_std , y)

In [13]:
n = [[4.9 , 3 , 1.4 , 0.2]]

In [14]:
model.predict(n)

array([2])

# Tasks
## 1- Explain Each in the logistic regression model:
#### Different Solvers params
#### Different Multiclass params
## 2- Calculate the accuracy of the model
## 3- Make manual standard scaling funcation from the calculated standard scaler of sklearn:

#### A- Make a function that takes a scaler as input and returns a json file with the scaling values as keys and values.

#### B- Make another function that takes the json file and the raw input and returns the input values after scaling.



------------------

# Answers:

### 1- Explain Each in the logistic regression model:

Different Solvers params:

- lbfgs (Default): Approximates the second derivative matrix updates. Good for multiclass problems and most standard datasets.

- liblinear: Uses a coordinate descent algorithm. Good for small datasets and handling L1 penalties. Only supports One-vs-Rest for multiclass.

- newton-cg: Uses a Newton-Raphson method (calculates the exact Hessian matrix). Handles L2 or no penalty and supports multiclass.

- sag: Stochastic Average Gradient descent. Faster for large datasets (both features and samples).

- saga: A variant of sag that also supports the L1 penalty (useful for sparse multinomial logistic regression).

- newton-cholesky: An exact Newton solver that is a good choice for datasets with far more samples than features.

Different Multiclass params:

- ovr (One-vs-Rest): Fits a separate binary classifier for each class against all other classes combined.
 
- multinomial: Minimizes the multinomial loss fit across the entire probability distribution. It calculates the joint probability of all classes simultaneously.

- auto: Automatically selects ovr if the solver is liblinear or if the data is binary; otherwise, it selects multinomial.

### 2- Calculate the accuracy of the model


In [15]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(x_std)

accuracy = accuracy_score(y, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%")

# Alternatively, using the built-in score method:
print(f"Model Accuracy: {model.score(x_std, y) * 100:.2f}%")

Model Accuracy: 94.67%
Model Accuracy: 94.67%


## 3- Make manual standard scaling funcation from the calculated standard scaler of sklearn:

#### A- Make a function that takes a scaler as input and returns a json file with the scaling values as keys and values.

#### B- Make another function that takes the json file and the raw input and returns the input values after scaling.

In [16]:
import json

def export_scaler_to_json(scaler, filename="scaler_params.json"):
    """Extracts mean and scale from a fitted StandardScaler and saves to JSON."""
    scaling_params = {
        "mean": scaler.mean_.tolist(),
        "scale": scaler.scale_.tolist()
    }
    
    with open(filename, 'w') as f:
        json.dump(scaling_params, f, indent=4)
        
    return scaling_params

params = export_scaler_to_json(sclaer, "scaler_params.json")
print(params)

{'mean': [5.843333333333335, 3.057333333333334, 3.7580000000000027, 1.199333333333334], 'scale': [0.8253012917851409, 0.43441096773549437, 1.7594040657753032, 0.7596926279021594]}


In [17]:
import numpy as np

def manual_transform(json_filename, raw_input):
    """Loads scaling params from JSON and applies standard scaling to raw input."""
    with open(json_filename, 'r') as f:
        params = json.load(f)
        
    mean = np.array(params["mean"])
    scale = np.array(params["scale"])
    raw_input_array = np.array(raw_input)
    
    scaled_output = (raw_input_array - mean) / scale
    
    return scaled_output

scaled_n = manual_transform("scaler_params.json", n)
print(scaled_n)
print(model.predict(scaled_n))

[[-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]]
[0]
